### ISSUE TITLE
Extract "Published" field from HPEVolumeInfo

### ISSUE THREAD

**Issue by ctolon22** [hpe-storage/csi-driver#225]
In our environment, we are using the Retain reclaim policy to keep PVs for a while in case a direct restart is necessary.

We have a golang script to remove Released PVs and the storage from 3 par in a control way. We would like to add a double check that the PV is released (information in the Kubernetes PV object) and is not published by this controller, information that I could recover from hpevolumeinfos.

It would be possible to retrieve this information in some way from hpevolumeinfos directly from golang? Instead of using unstructured dynamic client or requesting directly to the 3 par?

Thanks

**Comment by datamattsson** [comment]
@wdurairaj can you reassign this issue if you're not able to answer this?

**Comment by wdurairaj** [comment]
@ctolon22 , we have a code which contains the CRD struct for hpevolumeinfos. Unfortunately this is not opensource, and we can't share it here.. you can try some other scripted automation to retrieve this flag Published from hpevolumeinfos..

Alternatively, you can look at 3PAR array for the presence of vluns (which means published) and the absence with means unpublished.

`showvlun -v <pv-name> ` where pv-name is truncated to 31 chars (from the output of `kubectl get pv`)

**Comment by ctolon22** [comment]
Hi, thanks. I finally used Unstructured packge for extracting that field.

I'm closing the issue.
