### ISSUE TITLE
kubelet_volume* / persistent volume metrics

### ISSUE THREAD

**Issue by sunchill06** [hpe-storage/csi-driver#242]
I am trying to get kubelet_volume_* metrics., but don't see any.

Does HPE CSI supports PVC stats for volumes provisioned dynamically?

@raunakkumar, please help if possible.

**Comment by Baykonur** [comment]
As far as I can see, this was implemented. See [this PR](https://github.com/hpe-storage/csi-driver/pull/219/files) but HPE needs to update its [documentation](https://scod.hpedev.io/search.html?q=metrics) and deployment for helm-chart and other deployment options to annotate the `daemonset` so Prometheus can scrape this.

**Comment by datamattsson** [comment]
@Baykonur and @sunchill06 this is a feature that will become "available" in the docs in 1.5.0 (along with a few other things). Thank you for your patience.

**Comment by Baykonur** [comment]
Thanks @datamattsson, any timeline when v1.5 will be available?

**Comment by datamattsson** [comment]
Don't hold it against me but around May/June. ;-)

**Comment by sunchill06** [comment]
Thanks @datamattsson and @Baykonur . Really appreciate your inputs.
