### ISSUE TITLE
OpenShift 4.10 certification

### ISSUE THREAD

**Issue by nilic** [hpe-storage/csi-driver#316]
Hi, when can we expect OpenShift 4.10 certification? 

CSI driver version 2.1.1 supports Kubernetes 1.23 which is included in OpenShift 4.10 but the [OpenShift SCOD page](https://scod.hpedev.io/partners/redhat_openshift/index.html#certified_combinations) still doesn't include OCP 4.10 although it was released in March.

**Comment by unknownsolo** [comment]
Wondering about this as well!

**Comment by datamattsson** [comment]
We are currently working on OpenShift 4.10, it will be part of the next release of the CSI driver.

**Comment by unknownsolo** [comment]
Do you have an ETA by any chance? This is the only thing blocking us from upgrading to OpenShift 4.10

**Comment by datamattsson** [comment]
> Do you have an ETA by any chance? This is the only thing blocking us from upgrading to OpenShift 4.10

In the next few weeks.

**Comment by datamattsson** [comment]
Thanks @pipopopo! We're not doing a good job keeping this repo tidy.
