### ISSUE TITLE
Openshift 4.12 certification

### ISSUE THREAD

**Issue by milosvukmirovic** [hpe-storage/csi-driver#340]
We have a production Openshift cluster that we would like to upgrade from 4.10 to 4.12. Can you tell us when is Openshift 4.12 certification planned?

**Comment by datamattsson** [comment]
Once this has merged https://github.com/k8s-operatorhub/community-operators/pull/2463 we can start the process with Red Hat. We've completed all the work on our end for OpenShift 4.12 certification.

**Comment by siegy22** [comment]
@datamattsson This has been merged 3 weeks ago, any updates on this? 

Also, is it recommended to just install via Helm chart on OpenShift 4.12 as of now?

**Comment by datamattsson** [comment]
@sijeesh is responsible for creating the release, not sure what is holding things up.

**Comment by datamattsson** [comment]
Have you checked https://scod.hpedev.io/container_storage_provider/hpe_alletra_9000/index.html#remote_copy_with_peer_persistence_synchronous_replication_parameters?

**Comment by siegy22** [comment]
@sijeesh Any updates on this? :smile:

**Comment by datamattsson** [comment]
@siegy22 thanks for verifying. We've tested and verified OpenShift 4.13 already but it's not fully certified and probably won't be until the next release. Follow https://scod.hpedev.io/partners/redhat_openshift/index.html#certified_combinations for updates.
