### ISSUE TITLE
Alletra 9000 CSI Upload Data to Persistent Volume Claim  failed on  openshift 

### ISSUE THREAD

**Issue by Greco21298** [hpe-storage/csi-driver#346]
![image](https://github.com/hpe-storage/csi-driver/assets/120445010/e5f5c2c7-e463-4897-97d5-2aea098ae76e)
![image](https://github.com/hpe-storage/csi-driver/assets/120445010/b8483443-0796-4ab4-89ba-10504847179c)
I  think  this issue maybe hit https://github.com/hpe-storage/csi-driver/issues/295；but  it failed to  edit   add allowOverrides: nfsNamespace to storage  class  with  error below error:
Danger alert:An error occurred
Error "Forbidden: updates to parameters are forbidden." for field "parameters".
![image](https://github.com/hpe-storage/csi-driver/assets/120445010/93c744f3-001b-49e3-bfc6-0b4bb97d7a53)

**Comment by datamattsson** [comment]
We don't support OpenShift Virtualization yet and we would not support it with RWX/FileSystem. RWX/Block will be supported on Alletra 5/6K and Nimble in the next release of the CSI driver.

**Comment by Greco21298** [comment]
when  will  the  next CSI  DRIVER  release ?

**Comment by datamattsson** [comment]
Fixed in v2.4.1 using RWX Block.
