### ISSUE TITLE
Issues on node reboot - orphaned pods / unbound PVCs / Stale file handles

### ISSUE THREAD

**Issue by nin0-0** [hpe-storage/csi-driver#355]
We're running hpe-csi driver  on openshift 4.12

```
Aug 31 08:51:06 bl9258 kubenswrapper[7086]: E0831 08:51:06.746462    7086 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"87bf952a-94d5-4c70-8ee3-67d2792947b7\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=3
```
``` 
Aug 31 10:13:44 bl9261 kubenswrapper[7619]: E0831 10:13:44.307781    7619 pod_workers.go:965] "Error syncing pod, skipping" err="unmounted volumes=[toolsvm], unattached volumes=[toolsvm podinfo kube-api-access-sgjhk]: error processing PVC mavenirvsreprod-tool-cnf/toolsvm-pvc: PVC is not bound" pod="mavenirvsreprod-tool-cnf/toolsvm-0" podUID=ad20e07c-df37-4141-899b-b47c5a8ffd5d
``` 
And last time I even had stale file handles for the NFS server, I had to reboot again in the end.

```
time="2023-08-30T17:59:02Z" level=error msg="GRPC error: rpc error: code = Internal desc = unknown error when stat on /var/lib/kubelet/pods/81922b78-9a40-4083-8f41-a588042a7c97/volumes/kubernetes.io~csi/pvc-8644abf2-460d-4e5c-ab7e-33ea1e9dfc28/mount: lstat /var/lib/kubelet/pods/81922b78-9a40-4083-8f41-a588042a7c97/volumes/kubernetes.io~csi/pvc-8644abf2-460d-4e5c-ab7e-33ea1e9dfc28/mount: stale NFS file handle" file="utils.go:73"
```

I'm not sure which logs to provide more, these are the logs for the kubelet in the nodes. It's really paralysing when the nodes don't come up after cluster reboot. 

Is there an easy way to detect which pod is for which node in hpe-csi-driver namespace?

**Comment by datamattsson** [comment]
> We're running hpe-csi driver on openshift 4.12
> 
> ```
> Aug 31 08:51:06 bl9258 kubenswrapper[7086]: E0831 08:51:06.746462    7086 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"87bf952a-94d5-4c70-8ee3-67d2792947b7\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=3
> ```

This I haven't seen in a long time. The directory it's trying to remove is usually a file with these errors. I'm don't know the root cause but you can safely remove the file and these errors stop.

> 
> ```
> Aug 31 10:13:44 bl9261 kubenswrapper[7619]: E0831 10:13:44.307781    7619 pod_workers.go:965] "Error syncing pod, skipping" err="unmounted volumes=[toolsvm], unattached volumes=[toolsvm podinfo kube-api-access-sgjhk]: error processing PVC mavenirvsreprod-tool-cnf/toolsvm-pvc: PVC is not bound" pod="mavenirvsreprod-tool-cnf/toolsvm-0" podUID=ad20e07c-df37-4141-899b-b47c5a8ffd5d
> ```
> 

I have no idea what would cause a PVC to become unbound if it once was bound. Was the PVC ever bound?

> And last time I even had stale file handles for the NFS server, I had to reboot again in the end.
> 
> ```
> time="2023-08-30T17:59:02Z" level=error msg="GRPC error: rpc error: code = Internal desc = unknown error when stat on /var/lib/kubelet/pods/81922b78-9a40-4083-8f41-a588042a7c97/volumes/kubernetes.io~csi/pvc-8644abf2-460d-4e5c-ab7e-33ea1e9dfc28/mount: lstat /var/lib/kubelet/pods/81922b78-9a40-4083-8f41-a588042a7c97/volumes/kubernetes.io~csi/pvc-8644abf2-460d-4e5c-ab7e-33ea1e9dfc28/mount: stale NFS file handle" file="utils.go:73"
> ```

This is means the NFS client has a file open that the NFS server doesn't recognize or is unavailable.

> 
> I'm not sure which logs to provide more, these are the logs for the kubelet in the nodes. It's really paralysing when the nodes don't come up after cluster reboot.

Was this a planned or unplanned reboot? It's safest to drain nodes before rebooting.

> 
> Is there an easy way to detect which pod is for which node in hpe-csi-driver namespace?

`oc get nodes -o wide` will show you which Pod runs on which node. `oc get volumeattachments` will show you which PV is attached to which node.

**Comment by nin0-0** [comment]
We actually had a storage issue, where the iostack crashed during IOM replacement on the alletra - I think this is the PVC unbound one.

We are only doing cluster reboots on applying MachineConfigs or SR-IOV config (networkattachmentdefinition I believe?), which always drains the node when rebooting it - both provoke a cluster reboot.

Today our vendor reported the following (beware, I did online OCR, some chars are missing)
```
2m43s    Warning FailedAttachVolume pod/config-service-O                        AttachVolume.Attach failed for volume "pvc-fa467d34-0c42-4eca-9a9f-ccbOele8d 
bf2" : rpc error: code = Aborted desc = There is already an operation pending for the specified id ControllerPublishVolume:pvc-fa467d34-0c42-4eca-9a9f-ccbOele8dbf2:41c95b34-ba70-1ca5- 
cb74-1372c1810f05
2m43s    Warning FailedAttachVolume pod/et.cd-O                                 AttachVolume.Attach failed for volume "pvc-55755dcf-3fbc-403e-ab42-dedb253ec
4fc" : rpc error: code = Aborted desc = There is already an operation pending for the specified id ControllerPublishVolume:pvc-55755dcf-3fbc-403e-ab42-dedb253ec4fc:935d5lac-9e57-ca54- 
bc5d-656973f8d529
106s     Warning FailedMount        pod/etcd-O                                  Unable to attach or mount volumes: unmounted volumes=[etcd-vol], unattached
volumes=[etcd-vol etcd-config]: timed out waiting for the condition
103s     Warning FailedMount        pod/config-service-O                        Unable to attach or mount volumes: unmounted volumes=[config-service-vol], u
nattached volumes=[config-service-mgmt-cfg ramdisk-vol cim-config static-config kube-api-access-56cfp mnt-oam-sidecar config-service-vol]: timed out waiting for the condition
41s      Warning FailedAttachVolume pod/etcd-O                                  AttachVolume.Attach failed for volume "pvc-55755dcf-3fbc-403e-ab42-dedb253ec 
4fc" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
41s      Warning FailedAttachVolume pod/config-service-O                        AttachVolume.Attach failed for volume "pvc-fa467d34-0c42-4eca-9a9f-ccb0e1e8d
bf2" : rpc error: code = Internal desc = Failed to add ACL to volume pvc-fa467d34-0c42-4eca-9a9f-ccb0e1e8dbf2 for node &{ b19296 41c95b34-ba70-1ca5-cb74-1372c1810f05 [0xc000716a80] [0 
xc000716ac0 Oxc000716ad0 Oxc000716ae0] [Oxc000716b00 Oxc000716b10] } via CSP, err: Put "htto://
``` 

This was when deploying a new service and they had to try multiple times before it finally worked.

Remains the stale file handles of the NFS server, since I've encountered this multiple times. Also I've noticed that sometimes the operator fails to register to the alletra. Will need to back this by some logs preferably. If you have any lengthy and specific commands to specifically filter for this, feel free. 

Thanks for your support !

**Comment by datamattsson** [comment]
> 41s      Warning FailedAttachVolume pod/config-service-O                        AttachVolume.Attach failed for volume "pvc-fa467d34-0c42-4eca-9a9f-ccb0e1e8d
> bf2" : rpc error: code = Internal desc = Failed to add ACL to volume pvc-fa467d34-0c42-4eca-9a9f-ccb0e1e8dbf2 for node &{ b19296 41c95b34-ba70-1ca5-cb74-1372c1810f05 [0xc000716a80] [0 
> xc000716ac0 Oxc000716ad0 Oxc000716ae0] [Oxc000716b00 Oxc000716b10] } via CSP, err: Put "htto://

This needs to be investigated further. It could be a communications error between the CSI driver and CSP.

Is the array under a support contract? Can you work with your HPE rep to file a support case so we can prioritize this?

**Comment by nin0-0** [comment]
case opened 5376115048

**Comment by datamattsson** [comment]
@nin0-0 thanks, I've seen it and we have support engaged.

**Comment by nin0-0** [comment]
`timed out waiting for external-attacher of csi.hpe.com CSI driver to attach volume pvc-7b71248b-3627-4e60-8b5a-b334419c9191`
`Volume is already exclusively attached to one node and can't be attached to another`

our 2 outstanding issues - fyi here

Eventually the attachments work but it takes up to 15minutes

**Comment by datamattsson** [comment]
> `Volume is already exclusively attached to one node and can't be attached to another`

The RWO volumes can only be attached to one node at a time and don't support rolling upgrades.

**Comment by nin0-0** [comment]
The vendor is deleting the full deployment (helm uninstall <xyz>) and recreating, so no rolling update being applied. 

We're seeing the volumes getting attached eventually, but it takes a long time (up to 15 minutes) - is this expected behavior?

**Comment by nin0-0** [comment]
we added `hostseesvlun` parameter now for RWO - do we also need it for RWX?

and on cluster restart, still seeing e.g.:
`time="2023-09-27T10:44:51Z" level=error msg="GRPC error: rpc error: code = Internal desc = unknown error when stat on /var/lib/kubelet/pods/eaf40870-019e-48a3-92b3-081f423f139d/volumes/kubernetes.io~csi/pvc-f616a530-93d3-4320-86c9-b7d219f90442/mount: lstat /var/lib/kubelet/pods/eaf40870-019e-48a3-92b3-081f423f139d/volumes/kubernetes.io~csi/pvc-f616a530-93d3-4320-86c9-b7d219f90442/mount: stale NFS file handle" file="utils.go:73"`

**Comment by datamattsson** [comment]
`hostseesvlun` is set on the `StorageClass` spawning both RWX/RWO volumes but only really apply to the RWO volume.

> The vendor is deleting the full deployment (helm uninstall ) and recreating, so no rolling update being applied.

I meant applications leveraging PVCs.

> and on cluster restart, still seeing

Is this on existing or new NFS servers?

**Comment by nin0-0** [comment]
still seeing `stale file handles` and `orphaned pods` errors on cluster reboots. And when redeploying a resource a couple of times (but not removing the PVCs), we get `multi attach` error.

> hostseesvlun is set on the StorageClass spawning both RWX/RWO volumes but only really apply to the RWO volume.

Do you mean I do have to also set on my SC for RWX?

> The RWO volumes can only be attached to one node at a time and don't support rolling upgrades.
> I meant applications leveraging PVCs.

I have seen that it takes a while for larger volumes to get created and bound. Is this maybe why we're having issues when rebooting/recreating?

> Is this on existing or new NFS servers?

We only use the integrated NFS servers, but I guess there's only 1 NFS server on one node at any point. Might this be why it seemingly starts failing during a cluster reboot when it's draining one particular host? I thought this was mitigated by [pod monitor](https://scod.hpedev.io/csi_driver/monitor.html)?

**Comment by nin0-0** [comment]
> Oct 11 17:15:06 bl9278 kubenswrapper[6996]: W1011 17:15:06.831079    6996 empty_dir.go:523] Warning: Failed to clear quota on /var/lib/kubelet/pods/ec92b1bf-fd1c-4b46-99e2-aab4cbbdb942/volumes/kubernetes.io~configmap/config-volume: clearQuota called, but quotas disabled

Is this a relevant error or we can ignore?

**Comment by nin0-0** [comment]
do we need to configure this label for each deploy/statefulset using RWX / NFS server?

  template:
    metadata:
      labels:
        monitored-by: hpe-csi
        app: my-app

**Comment by datamattsson** [comment]
I'm on vacation and unable to reply in the coming weeks. The Pod Monitor is
mainly for apps using RWO PVCs, not NFS/RWX PVCs.

**Comment by dileepds** [comment]
> still seeing `stale file handles` and `orphaned pods` errors on cluster reboots. And when redeploying a resource a couple of times (but not removing the PVCs), we get `multi attach` error.
> 
> > hostseesvlun is set on the StorageClass spawning both RWX/RWO volumes but only really apply to the RWO volume.
> 
> Do you mean I do have to also set on my SC for RWX?

Yes you can set it for SC of RWX PVCs if it is using storage from Alletra.

> > The RWO volumes can only be attached to one node at a time and don't support rolling upgrades.
> > I meant applications leveraging PVCs.
> 
> I have seen that it takes a while for larger volumes to get created and bound. Is this maybe why we're having issues when rebooting/recreating?
> 
Yes Its Possible. 
> > Is this on existing or new NFS servers?
> 
> We only use the integrated NFS servers, but I guess there's only 1 NFS server on one node at any point. Might this be why it seemingly starts failing during a cluster reboot when it's draining one particular host? I thought this was mitigated by [pod monitor](https://scod.hpedev.io/csi_driver/monitor.html)?

By Default if there are no explicit lablels  hpe-csi driver considers all the available worker nodes to spin up nfs-server pod, [ https://scod.hpedev.io/csi_driver/using.html#using_the_nfs_server_provisioner  ]

**Comment by dileepds** [comment]
> > Oct 11 17:15:06 bl9278 kubenswrapper[6996]: W1011 17:15:06.831079    6996 empty_dir.go:523] Warning: Failed to clear quota on /var/lib/kubelet/pods/ec92b1bf-fd1c-4b46-99e2-aab4cbbdb942/volumes/kubernetes.io~configmap/config-volume: clearQuota called, but quotas disabled
> 
> Is this a relevant error or we can ignore?

I think the error is not related to PVCs , it seems like an error about config maps .

**Comment by nin0-0** [comment]
>         The RWO volumes can only be attached to one node at a time and don't support rolling upgrades.
>         I meant applications leveraging PVCs.
> 
>     I have seen that it takes a while for larger volumes to get created and bound. Is this maybe why we're having issues when rebooting/recreating?
> 
> Yes Its Possible.

I've added hostseesvlun to the nfs SC now, will come back

**Comment by nin0-0** [comment]
On cluster reboot now we're seeing:
`Warning  FailedMount             10m                  kubelet                  MountVolume.SetUp failed for volume "pvc-8fa08040-6717-4109-aff1-adb1da95902e" : rpc error: code = Internal desc = Error mounting nfs share 172.30.18.86:/export at /var/lib/kubelet/pods/0cc6caf6-1abf-48e6-86c1-ce97431fa5cb/volumes/kubernetes.io~csi/pvc-8fa08040-6717-4109-aff1-adb1da95902e/mount, err error command mount with pid: 257 killed as timeout of 60 seconds reached
 `
And one pod's container is creating state, stuck:
`hpe-nfs                                            pod/hpe-nfs-8fa08040-6717-4109-aff1-adb1da95902e-6c46c8cf45-cdpcb           0/1     ContainerCreating        0                38m     <none>          bl9279                                   <none>           <none>`

`  Warning  FailedAttachVolume  90s (x4 over 15m)      attachdetach-controller  (combined from similar events): AttachVolume.Attach failed for volume "pvc-d94e9949-f273-49b7-a02b-f14888723f7e" : rpc error: code = Internal desc = Failed to add ACL to volume pvc-d94e9949-f273-49b7-a02b-f14888723f7e for node &{ bl9279 782ef740-5fee-9b5c-ec27-77d233a22990 [0xc00050ad80] [0xc00050adc0 0xc00050add0 0xc00050ade0] [0xc00050ae40 0xc00050ae50]  } via CSP, err: Request failed with status code 400 and errors Error code (Bad Request) and message (HTTP error response from backend {"code":43,"desc":"invalid input: number exceeds expected range","ref":"lun"})
  Warning  FailedMount         80s (x14 over 36m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[hpe-nfs-8fa08040-6717-4109-aff1-adb1da95902e], unattached volumes=[hpe-nfs-8fa08040-6717-4109-aff1-adb1da95902e hpe-nfs-config kube-api-access-jphcc]: timed out waiting for the condition`

Any ideas?

**Comment by nin0-0** [comment]
```  Warning  FailedMount  5s (x4 over 23s)  kubelet            MountVolume.SetUp failed for volume "pvc-df6e71ca-1df7-4a5a-96cd-1a1c6454341d" : rpc error: code = Internal desc = Error mounting nfs share 172.30.55.198:/export at /var/lib/kubelet/pods/b665ee7f-3aa0-41ab-9242-4cf429d1d26b/volumes/kubernetes.io~csi/pvc-df6e71ca-1df7-4a5a-96cd-1a1c6454341d/mount, err fork/exec /chroot/mount: resource temporarily unavailable

and seeing this:
```
[root@bl1459 ticams003]# oc get po -n hpe-nfs -o wide
NAME                                                            READY   STATUS              RESTARTS   AGE     IP              NODE     NOMINATED NODE   READINESS GATES
hpe-nfs-081ecb26-831f-422f-8644-8900114793f6-758d4ccc77-8fvzn   1/1     Running             0          8d      172.16.30.24    bl9279   <none>           <none>
hpe-nfs-3416f79d-60e1-4b7e-a65b-34506e69d9a3-546f94b57c-z2qlg   1/1     Running             0          8d      172.16.31.250   bl9279   <none>           <none>
hpe-nfs-342333d0-d01f-4eb3-bb95-fc09960b4778-5cb9886f5f-5w7zh   1/1     Running             0          8d      172.16.30.28    bl9279   <none>           <none>
hpe-nfs-3aee3a42-6564-4045-8921-dfc42c743139-7768fc886f-stxl5   1/1     Running             0          8d      172.16.30.51    bl9279   <none>           <none>
hpe-nfs-45040c1b-2ab0-473b-a3ec-fc6bc7bb157d-5d6848d48c-brrfp   1/1     Running             0          8d      172.16.30.39    bl9279   <none>           <none>
hpe-nfs-476fbea8-229f-4254-bef3-cf46d3a4f2cf-86c6cb9997-vqhh5   1/1     Running             0          8d      172.16.30.50    bl9279   <none>           <none>
hpe-nfs-57664a80-0921-462e-a827-248d64bd66cf-56c6ff7797-dhqrm   1/1     Running             0          8d      172.16.30.45    bl9279   <none>           <none>
hpe-nfs-66600fc8-4a48-440f-ab4b-8b5f780480f4-6b575cbf6f-sr22j   1/1     Running             0          8d      172.16.30.37    bl9279   <none>           <none>
hpe-nfs-7564d89c-c8e7-471c-b12d-97ea6d8599a4-6564f749f7-rj4n6   1/1     Running             0          8d      172.16.31.251   bl9279   <none>           <none>
hpe-nfs-8fa08040-6717-4109-aff1-adb1da95902e-6c46c8cf45-hskdx   0/1     ContainerCreating   0          3h31m   <none>          bl9273   <none>           <none>
hpe-nfs-9aeb8ba1-a70a-47cf-bfe1-c5b903591485-6d4b57f47f-fvbw4   1/1     Running             0          8d      172.16.30.32    bl9279   <none>           <none>
hpe-nfs-9b1dc917-49f8-46da-8e55-0da01e685330-d5fc5c9c7-65m8j    1/1     Running             0          8d      172.16.30.44    bl9279   <none>           <none>
hpe-nfs-aacd8ea9-ee20-4d46-b520-b1401f911df1-596f8b888f-8bhhd   1/1     Running             0          8d      172.16.30.55    bl9279   <none>           <none>
hpe-nfs-ac6f85cf-dc1c-4571-b510-4d4f02b12954-6fc55458f7-h2wfk   1/1     Running             0          8d      172.16.30.48    bl9279   <none>           <none>
hpe-nfs-ae1438b0-ecab-454a-a3c9-5403e73a600a-5d47db879f-tpnpl   1/1     Running             0          8d      172.16.30.34    bl9279   <none>           <none>
hpe-nfs-b1ae7789-6111-4d3f-ad20-ecfff97f4620-86979bfc85-j7fcv   1/1     Running             0          8d      172.16.30.33    bl9279   <none>           <none>
hpe-nfs-b76bdfb3-5e11-463e-bfd6-60d74115ab37-6877ff59b5-nmrf8   1/1     Running             0          8d      172.16.30.42    bl9279   <none>           <none>
hpe-nfs-b8438a6b-3dbc-44e4-ab4a-2d1853587233-54c4c698b7-nrbb9   1/1     Running             0          8d      172.16.30.35    bl9279   <none>           <none>
hpe-nfs-d9168e58-2a17-490a-9253-07d40999c5e5-57f5758c5f-54nlc   1/1     Running             0          8d      172.16.30.43    bl9279   <none>           <none>
hpe-nfs-df6e71ca-1df7-4a5a-96cd-1a1c6454341d-6f99f7558f-fbshr   1/1     Running             0          8d      172.16.30.40    bl9279   <none>           <none>
hpe-nfs-eaff5f8f-dedd-46a1-9ce0-63f8f75593c8-76bb66b8cf-9lf45   1/1     Running             0          8d      172.16.30.52    bl9279   <none>           <none>
hpe-nfs-f60b695f-bc6c-4864-80a1-df26e660fb81-56799bf6d7-wjskp   1/1     Running             0          8d      172.16.30.58    bl9279   <none>           <none>
hpe-nfs-fd0b1265-e869-44b3-87c1-9121da90c995-75476d8db9-pkd85   1/1     Running             0          8d      172.16.30.46    bl9279   <none>           <none>

**Comment by datamattsson** [comment]
```
CSP, err: Request failed with status code 400 and errors Error code (Bad Request) and message (HTTP error response from backend {"code":43,"desc":"invalid input: number exceeds expected range","ref":"lun"})
```
This is interesting, can we get the logs from the CSP to see the full context of this request?

**Comment by nin0-0** [comment]
Seemingly the `allowMutations` is not consistently working to add the `hostSeesVLUN` to the existing PVCs.

I've not (with help of HPE support) added it for all PVCs in all namespace with a little script.

Should I remove allowMutations ?

**Comment by datamattsson** [comment]
Did you follow the steps and caveats here: https://scod.hpedev.io/container_storage_provider/hpe_alletra_9000/index.html#vlun_templates ?

**Comment by nin0-0** [comment]
I hadn't read this correctly (and not at all at first, I was following HPE support instructions). Thanks for the pointer !

**Comment by nin0-0** [comment]
no issues anymorethanks a lot for the help
