### ISSUE TITLE
Vanilla flavor

### ISSUE THREAD

**Issue by sofixa** [hpe-storage/csi-driver#365]
Hey everyone,

There is a (`vanilla`)[https://github.com/hpe-storage/csi-driver/tree/8874fe968539c6f42c2d7fa6eccd52b584cdf0a8/pkg/flavor/vanilla] (so non-Kubernetes) flavor of this CSI plugin. which seems to be mostly empty boilerplate (including in parts which can totally be implemented without any Kubernetes, like GetChapXFromEnvironment, cf. https://github.com/hpe-storage/csi-driver/blob/8874fe968539c6f42c2d7fa6eccd52b584cdf0a8/pkg/flavor/vanilla/flavor.go#L107-L113). 

Is there a way to get this plugin to work on non-Kubernetes environments? Mostly thinking of (Nomad)[https://www.nomadproject.io/]. It successfully runs, but I'm not sure it would actually do anything going off the vanilla/flavor.go.

Cheers,
Adrian

**Comment by datamattsson** [comment]
Theoretically the driver would run on Nomad and other non-Kubernetes environments but the CSI driver would still need access to a Kubernetes cluster to store and manage metadata in CRDs. So, this is a non-starter for most projects.

**Comment by sofixa** [comment]
@datamattsson since there are flavours handled in the code, shouldn't it be possible to pass this metadata in other ways?

**Comment by datamattsson** [comment]
Anything is possible, I'm just stating how things sit today.

**Comment by sofixa** [comment]
As far as I understand things, it's other things around the CSI plugin (like the operator) that translate those CRDs and annotations to native gRPC CSI calls, which the CSI plugin handles. If the CSI plugin is compatible with the CSI spec, it should just work out of the box with any other CSI-compatible orchestrator (as long as there is a way to pass the same metadata that is configured via CRDs in Kubernetes). 

In any case, I'm trying this out one stumbling block at a time and will report back. I was hoping there was some doc hidden somewhere - after all, the plugin authors bothered implementing a `vanilla` flavour in the first place.

**Comment by datamattsson** [comment]
> after all, the plugin authors bothered implementing a `vanilla` flavour in the first place.

Yes, the plans were grand. One storage framework to rule them all. The CRD I mention, HPENodeInfos, is abstracted in flavor.go through some of the functions. You just have to store that data in your CO somewhere and write a function to store and retrieve it.

Bear in mind that this is just the CSI driver. The CSPs (backends) are notorious for performing layer violations. The 3PAR CSP as an example, accesses the Kubernetes API directly to manage its own CRDs for various metadata resources, so if you're using a 3PAR-based backend, you will have to write a 3PAR CSP that doesn't break the rules as well.

**Comment by sofixa** [comment]
Agreed, currently configuring nodes is either "do it yourself" or weird tricks like mounting host paths and `bash`ing away. A declarative API for that part would be amazing. I'll check out the podcast you linked, sound good on paper, although Talos' Kubernetes exclusive focus makes me somewhat doubtful they would actively work to support other orchestrators.
