### ISSUE TITLE
The `hpe-csi-node` DaemonSet is way too invasive and does not work on RHEL/CentOS/Fedora Atomic.

### ISSUE THREAD

**Issue by Logibox** [hpe-storage/csi-driver#51]
RHEL/CentOS/Fedora Atomic has a immutable filesystem so you can't inject systemd units or install packages. Why isn't `iscsid` and `multipathd` provided by the container?

**Comment by shivamerla** [comment]
@Logibox So far we haven't verified our drivers on Atomic host or CoreOS. In CoreOS both iSCSI and multipath packages are already pre-installed with base image. I believe with RedHat Atomic Host 7.2.2 both are pre-packaged as well. We will handle these and bypass package installation from our systemd scripts. We will also look into allowing users to control package installation by the driver.

**Comment by shivamerla** [comment]
@Logibox we have added env param DISABLE_NODE_CONFORMANCE, when passed to node-plugin it will by-pass node conformance checks. Once we add support for CoreOS/Atomic we will update those YAML/deployment files accordingly.
