### ISSUE TITLE
Specifying volume parameters at the PVC

### ISSUE THREAD

**Issue by Logibox** [hpe-storage/csi-driver#52]
I would like to specify volume parameter when creating a PVC, rather that having an array of different StorageClasses. It's not clear from the docs whether this is possible.

**Comment by suneeth51** [comment]
We have "allowOverride" parameter in the storage class. With this, you can override the volume parameters in the PVC spec.

Please refer to "Test and verify Persistent Volume Claim overrides" in https://github.com/hpe-storage/csi-driver/blob/master/USING.md for more details/examples.

**Comment by Logibox** [comment]
Ah just what I'm looking for! Thanks
