### ISSUE TITLE
Handle empty login token

### ISSUE THREAD

**Issue by tobad357** [hpe-storage/csi-driver#64]
Currently if the csi-driver fails a login it will send an empty token to the csp. Which in turn errors out. The csi-driver should probably try to login again until it has a valid token and if it can't login show an appropriate error message

**Comment by suneeth51** [comment]
Created the PR for the fix:
https://github.com/hpe-storage/common-host-libs/pull/76

**Comment by suneeth51** [comment]
Merged the PR: hpe-storage/common-host-libs#76
