### ISSUE TITLE
Volumeattachment stays on crashed node

### ISSUE THREAD

**Issue by tobad357** [hpe-storage/csi-driver#68]
If node1 crashed the volumeattachment will stay there despite pods from node1 trying to start on node2. 
The pods will then get a ""Multi-Attach error for volume"" when coming up.
The only way to fix this is to delete the volumeattachment by hand

Expected behavior is to be inline with the in tree iscsi provider which leaves multi attach issues to be handled by Nimble. That way when it comes up it will be allowed to login to the volume once the old session has timed out

**Comment by tobad357** [comment]
Potentially one way to solve this would be for the hpe-csi-controller to reconcile volumeatatchments with pods on the node it is pointing to.
if no pod in running, starting etc state exists then the volumeattachment should be dettached
Once node comes back it should remove the volumeattachment

**Comment by tobad357** [comment]
I think this may be related to
https://github.com/kubernetes/kubernetes/issues/65392

**Comment by shivamerla** [comment]
@tobad357 closing this issue a this is not specific to our csi driver, but something being worked upon by the community.
